ftp_User:qaftp
ftP_pass:Ftp$QA@Ad3pt!a
ftPHost111:ftp2.adeptia.com
port:21
ftpsrcpath:/bharat/Source/FTP_Source
ftpsrcfile:StringFunction.txt
ftptrgpath:/bharat/Target/FTP_Trg
ftptrgfilename: bd_git_target.txt
ASB@QABus@AAD@Host:adeptiaqabus.servicebus.windows.net
SB@QABus@AAD@CID:1b6b0dbd-ca82-47f1-b307-1e4f28b73c66
SB@QABus@AAD@CSecret:
SB@QABus@AAD@TenantID:45549897-61ee-4cfa-b596-04ca9df5c105
Incoming_Mail_Server:imap.gmail.com
mail_port:993
Sender_E_mail:akash.giri@adeptia.com
mail_subject:AG_Mail_Source_Basic_IMAP_TLS_Vault_Config
mail_file_name:Contact.xml

Native Call
NativeCall_FileName:/Krati/shell.sh
NativeCall_Argument:ARGUMENT 
NativeCall_WorkDirctory:Directory
AZFile_StorageActName: adeptiaqateam
FileShareName: adpqa
AzBlob_ContainerName: vishal

AS3_AWSAccessKeyID: AKIA2NZ4CEGHRKUYRYXQ

Kafka_Account_Broker: kafka-0.kafka-headless.kafka2.svc.cluster.local:9092

JMS_URL: tcp://172.177.207.77:61616
JMS_UserName: admin
JMS_Password: admin
Azblb_clientid111: 3bb20b54-4c1f-4caf-a253-7c4663cade4c
Azblb_tenantid: 45549897-61ee-4cfa-b596-04ca9df5c105

bd_sqldb_serverURL: jdbc:sqlserver://customdevmi.public.dededc70fdf0.database.windows.net:3342;database=sv_solution;Authentication=ActiveDirectoryPassword;encrypt=true;trustServerCertificate=true;
bd_sqldb_user: qateam@adeptia0.onmicrosoft.com
bd_sqldb_pass: nI<8U32Fa_mpp
bd_sqldb_schemaname: dbo
